# Generated by Django 4.1.2 on 2022-10-11 22:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_empleado_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='hoja_de_vida',
            field=ckeditor.fields.RichTextField(default='texto de prueba'),
            preserve_default=False,
        ),
    ]
